### PR TITLE
Moved html files to new folder

### PR DESCRIPTION
**Pull request by shaurya5**
Moved html files to pages/html/src and changed the src links in js and HTML files.

### CODE REVIEW

**Comment by ADI10HERO** [comment]
Hey @shaurya5, I think there's some misunderstanding :( 
The HTML files were to be moved to pages "or" HTML "or" src folders not pages/html/src like the literal sense of folder-tree. Like whichever you see fit.

**Comment by shaurya5** [comment]
> Hey @shaurya5, I think there's some misunderstanding :( 
> The HTML files were to be moved to pages "or" HTML "or" src folders not pages/html/src like the literal sense of folder-tree. Like whichever you see fit.
> 
> 

oh ok.. so you want every html file except index.html, in a single folder, right?

**Comment by ADI10HERO** [comment]
> > Hey @shaurya5, I think there's some misunderstanding :(
> > The HTML files were to be moved to pages "or" HTML "or" src folders not pages/html/src like the literal sense of folder-tree. Like whichever you see fit.
> 
> oh ok.. so you want every html file except index.html, in a single folder, right?

Yes, that's correct.

**Comment by shaurya5** [comment]
@ADI10HERO made a new commit. Please check

**Comment by shaurya5** [comment]
@ADI10HERO if the commits are okay this time, please merge the change

**Comment by ADI10HERO** [comment]
Hey @shaurya5, did you test your changes?

**Comment by ADI10HERO** [comment]
Anyway, the PR breaks a lot of website functionality and we decided to leave the HTML files as it is for now.. 
Please take up other issues :) (github.com/Auto-DL) 

Thank you so much for contributing! 😄

**Pull request closed without merging**
