### PR TITLE
[Fixes #30] Fix Text Padding

### LINKED ISSUE #30: Fix Text Padding/Margin/Spacing
image

**Title Text ("The") should start along the navbar not before it :)**

### PR DESCRIPTION
**Pull request by Halix267**
fixes #30

### CODE REVIEW

**Comment by Halix267** [comment]
@ADI10HERO .Plz review it

**Comment by ADI10HERO** [comment]
see #3

**Comment by ADI10HERO** [comment]
Merging for now, but we could've done better than hardcoding the pixel values :)

**Comment by ADI10HERO** [comment]
give @Halix267 5 points

**Pull request merged**
