### PR TITLE
[Fixes #4] Removed "chat on gitter" badge from README

### LINKED ISSUE #4: Remove "chat on gitter" badge from Readme

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
fixes #4

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@ADI10HERO please review it.

**Review by ADI10HERO — APPROVED** [review]
Thanks for the quick PR

**Comment by ADI10HERO** [comment]
give @Vrindagupta6828 5 points

**Comment by ADI10HERO** [comment]
give @Vrindagupta6828 5 points

**Comment by ADI10HERO** [comment]
give @Vrindagupta6828 5 points

**Comment by ADI10HERO** [comment]
@Vrindagupta6828  did you delete the source repository? Can you please resolve the conflict?

**Review by ADI10HERO — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by Vrindagupta6828** [comment]
> @Vrindagupta6828 did you delete the source repository? Can you please resolve the conflict?

yes i have deleted that

**Comment by Vrindagupta6828** [comment]
i will have to do that again with another branch

**Comment by ADI10HERO** [comment]
So is it okay if I close the PR?

**Comment by Vrindagupta6828** [comment]
> So is it okay if I close the PR?

yes.
so i should do it again right?

**Comment by ADI10HERO** [comment]
No no its okay :)

**Comment by ADI10HERO** [comment]
Thank you for the PR, closing this now :)

**Pull request closed without merging**
