### PR TITLE
Updates theme meta tag and scrollbar #51

### PR DESCRIPTION
**Pull request by niyoj**
# Fixes issue #51 

## Summary of the changes
- In `index.html` inside `<head>` tag a new meta tag was added for the theme of the website,
- The scroller color blended with the background so, I changed its color to vibrant pink color which is also used in the website previously.

### CODE REVIEW

**Comment by niyoj** [comment]
@ADI10HERO Here is my original PR.

**Comment by ADI10HERO** [comment]
Hey, your scrollbar change was merged and I would make a  "new" PR with just the theme color change and close this one.
Thanks :)

**Comment by niyoj** [comment]
@ADI10HERO Can you merge this one as it will be counted as +1 PR in Hacktoberfest for Auto DL? OR `hacktoberfest-accepted` label will be very great for me.

**Comment by ADI10HERO** [comment]
Closing this due to lack of activity. Will re-open if required. (follow up on slack)

**Pull request closed without merging**
